### ISSUE TITLE
Geting too many redirects error

### ISSUE THREAD

**Issue by DKC03** [fspijkerman/dash-cognito-auth#17]
Hi @fspijkerman / @MauriceBrg  ,
Thank you for the package. I'm currently working on integrating it with my project, which is hosted on AWS using ALB, Fargate, and Cognito. Please refer to the screenshot for my setup.
After successfully logging in, I encounter a 'too many redirect errors'. Could you advise if there might be any mistakes in my setup?
Setup:
![Screenshot 2024-04-26 at 1 10 32 PM](https://github.com/fspijkerman/dash-cognito-auth/assets/150807395/cbf41dd0-d78d-4133-9ebb-2b442077bf4a)
Network:
![image](https://github.com/fspijkerman/dash-cognito-auth/assets/150807395/18933f86-dc25-42d0-a640-d5e65aa614b0)

Also i'm getting the following waring on my server
```
/usr/local/lib/python3.10/site-packages/werkzeug/sansio/response.py:224: 
The 'session' cookie is too large: the value was 4315 bytes but the header required 26 extra bytes. The final size was 4341 bytes but the limit is 4093 bytes. Browsers may silently ignore cookies larger than this.
```

**Comment by MauriceBrg** [comment]
Hey,

if I recall correctly that's most likely because there's more info in the Cognito auth data, i.e. the JWT than can fit in the session cookie.

This means it will try to validate the session cookie after login, realize it is broken/invalid and then re-initiate the login process, cognito knows that you're logged in and redirects you to the app, which starts the process all over again. This is how you end up at too many redirects.

I believe the information that's put into the session cookie is handled by the underlying `flask-dance` library so I'm not sure if we can do much about that, but I can look into it in the future.

I usually use an external session storage, e.g. the filesystem or DynamoDB to store the session info server-side - [`flask-session`](https://github.com/pallets-eco/flask-session) is a good candidate for that.

**Comment by DKC03** [comment]
@MauriceBrg  flask-session works for me, Thanks for your quick response.
